import { useEffect, useState } from "react";
import { Bell, Check, LockKeyhole, Palette, Save, ShieldCheck } from "lucide-react";

const defaults = { emailUpdates:true, applicationReminders:true, publicPortfolio:true, compactMode:false };
export default function Settings() {
  const [settings,setSettings]=useState(()=>{try{return {...defaults,...JSON.parse(localStorage.getItem("westforce_settings")||"{}")};}catch{return defaults;}});
  const [saved,setSaved]=useState(false);
  const toggle=(key)=>setSettings((s)=>({...s,[key]:!s[key]}));
  const save=()=>{localStorage.setItem("westforce_settings",JSON.stringify(settings));setSaved(true);setTimeout(()=>setSaved(false),2200);};
  return <div className="dashboard-product"><header className="product-page-header"><div><span className="product-eyebrow">ACCOUNT</span><h1>Settings</h1><p>Control notifications, sharing preferences and the appearance of your career workspace.</p></div></header>{saved&&<div className="product-notice"><Check size={15}/><span>Settings saved in this browser.</span></div>}<section className="product-card"><div className="product-card-header"><div><h2>Preferences</h2><p>These controls are local demo settings until a Settings model is connected.</p></div></div><Setting icon={Bell} title="Email updates" text="Receive product and resume workflow updates." checked={settings.emailUpdates} onChange={()=>toggle("emailUpdates")}/><Setting icon={Bell} title="Application reminders" text="Show reminders for application follow-ups." checked={settings.applicationReminders} onChange={()=>toggle("applicationReminders")}/><Setting icon={ShieldCheck} title="Public portfolio" text="Allow your published portfolio to be shared by URL." checked={settings.publicPortfolio} onChange={()=>toggle("publicPortfolio")}/><Setting icon={Palette} title="Compact workspace" text="Use a denser layout for dashboard cards." checked={settings.compactMode} onChange={()=>toggle("compactMode")}/><button className="product-button primary" style={{marginTop:18}} onClick={save}><Save size={14}/> Save Settings</button></section><div className="product-dashboard-grid" style={{marginTop:18}}><div className="product-card"><div className="product-stat-icon"><LockKeyhole size={18}/></div><h3 style={{margin:"14px 0 5px",color:"#17344e"}}>Authentication</h3><p style={{margin:0,fontSize:11,color:"#7e91a4"}}>Firebase Authentication remains the account identity provider.</p></div><div className="product-card"><div className="product-stat-icon"><ShieldCheck size={18}/></div><h3 style={{margin:"14px 0 5px",color:"#17344e"}}>Data architecture</h3><p style={{margin:0,fontSize:11,color:"#7e91a4"}}>MongoDB stores application data and Cloudinary stores uploaded files.</p></div></div></div>;
}
function Setting({icon:Icon,title,text,checked,onChange}){return <label style={{display:"flex",alignItems:"center",gap:13,padding:"15px 0",borderTop:"1px solid #edf1f5",cursor:"pointer"}}><span className="product-stat-icon"><Icon size={16}/></span><span style={{flex:1}}><strong style={{display:"block",fontSize:12,color:"#17344e"}}>{title}</strong><small style={{display:"block",marginTop:3,fontSize:10,color:"#8999aa"}}>{text}</small></span><input type="checkbox" checked={checked} onChange={onChange} style={{accentColor:"#087fbe",width:17,height:17}}/></label>}
